[phases.setup]
nixPkgs = [
  "default-libmysqlclient-dev",
  "g++",
  "gcc", 
  "libffi-dev", 
  "pkg-config",
  "python311"
]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "mkdir -p static staticfiles media",
  ". /opt/venv/bin/activate && python manage.py collectstatic --noinput"
]

[start]
cmd = ". /opt/venv/bin/activate && python manage.py migrate && python manage.py setup_oauth && gunicorn main.wsgi:application"
