# Generated by Django 5.2.3 on 2025-09-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_resourcecategory_resourceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceitem',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='resources/pdfs/'),
        ),
    ]
