# Generated by Django 5.2.3 on 2025-09-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_resourceitem_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resources/images/'),
        ),
    ]
