# Generated by Django 5.2.3 on 2025-09-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_resourceitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='ResourceCategory',
        ),
        migrations.DeleteModel(
            name='ResourceItem',
        ),
    ]
