# Generated by Django 5.2.3 on 2025-08-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_add_google_social_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
