# Generated by Django 5.2.3 on 2025-08-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-viewed_on'], 'verbose_name_plural': 'Histories'},
        ),
    ]
