# Generated by hand to add AIContentSuggestion model
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_aijob_stage_name_alter_aijob_payload_pipelinerun_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIContentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('tool', 'Tool'), ('resource', 'Resource')], db_index=True, default='tool', max_length=50)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('short_description', models.TextField(blank=True)),
                ('detailed_metadata', models.JSONField(blank=True, default=dict)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('url', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('quality_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='pending_review', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='admin_portal.pipelinerun')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='ai_suggestions', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='ai_suggestions_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Content Suggestion',
                'verbose_name_plural': 'AI Content Suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
