# Generated by Django 5.2.3 on 2026-08-19 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0005_create_default_aipreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicontentsuggestion',
            name='pipeline_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_portal.pipelinerun'),
        ),
    ]
