# Generated by Django 5.2.3 on 2025-08-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_researchinterest_alter_userprofile_options_and_more'),
    ]

    operations = [
    ]
