# Generated by Django 5.2.3 on 2025-07-17 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-tools', help_text="FontAwesome icon class (e.g., 'fas fa-microscope', 'fas fa-chart-bar')", max_length=50)),
                ('color', models.CharField(default='#667eea', help_text='Hex color code for category card', max_length=7)),
                ('order', models.IntegerField(default=0, help_text='Order in which categories appear')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tool Category',
                'verbose_name_plural': 'Tool Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.CharField(help_text='Brief description shown on tool cards', max_length=300)),
                ('url', models.URLField(help_text='External URL where the tool is hosted')),
                ('tool_type', models.CharField(choices=[('web', 'Web-based Tool'), ('download', 'Downloadable Software'), ('api', 'API Service'), ('database', 'Database/Resource'), ('standalone', 'Standalone Application')], default='web', max_length=20)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('license', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Tool logo/icon (recommended: 200x200px)', null=True, upload_to='tool_logos/')),
                ('screenshot', models.ImageField(blank=True, help_text='Tool screenshot (optional)', null=True, upload_to='tool_screenshots/')),
                ('requirements', models.TextField(blank=True, help_text='System requirements or prerequisites')),
                ('features', models.TextField(blank=True, help_text='Key features (one per line)')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('click_count', models.IntegerField(default=0)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_tools', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tools', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='tools.toolcategory')),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='tools.tool')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool Click',
                'verbose_name_plural': 'Tool Clicks',
            },
        ),
    ]
