# Generated by Django 5.2.3 on 2025-07-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_analysishistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcategory',
            name='category_type',
            field=models.CharField(choices=[('organism', 'Organism Specific'), ('general', 'General Use')], default='general', help_text='Choose if this category is for general use or organism specific tools', max_length=10),
        ),
    ]
