# Generated by Django 5.2.3 on 2025-08-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_toolcategory_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysishistory',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='analysis_results/'),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
