# Generated by Django 5.2.3 on 2025-08-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_analysishistory_completed_at_and_more'),
    ]

    operations = [
    ]
