# Generated by Django 5.2.3 on 2025-09-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_auto_20250809_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcategory',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Long, detailed description for this category. Shown at the top of the category page.'),
        ),
    ]
