# Generated by Django 5.2.3 on 2026-06-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_auto_20250907_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tool',
            name='short_description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_type',
            field=models.CharField(choices=[('web', 'Web-based Tool'), ('download', 'Downloadable Software'), ('api', 'API Service'), ('database', 'Database/Resource'), ('standalone', 'Standalone Application')], db_index=True, default='web', max_length=20),
        ),
        migrations.AlterField(
            model_name='tool',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='category_type',
            field=models.CharField(choices=[('organism', 'Organism Specific'), ('general', 'General Use')], db_index=True, default='general', max_length=10),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='color',
            field=models.CharField(default='#667eea', max_length=7),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='detailed_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='icon',
            field=models.CharField(default='fas fa-tools', max_length=50),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
