# Generated by Django 5.2.3 on 2026-07-14 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_alter_tool_name_alter_tool_short_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisHistory',
        ),
    ]
