# Generated by Django 5.2.3 on 2025-09-04 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text="FontAwesome icon class, e.g. 'fas fa-book'", max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('link_icon', models.CharField(blank=True, help_text="FontAwesome icon class, e.g. 'fas fa-download'", max_length=50)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='resources/pdfs/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='resources/images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resources.resourcecategory')),
            ],
        ),
    ]
