# Generated by Django 5.2.3 on 2026-06-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resourceitem',
            name='link_icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='resourceitem',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
